[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
runOnSave = true    # 저장 시 자동 새로고침

[theme]
backgroundColor = "rgba(248, 247, 252, 0.93)"
primaryColor = "#069ff8b9"
secondaryBackgroundColor="rgba(184, 226, 230, 1)"
textColor = "#13052cf1"
