[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
runOnSave = true    # 저장 시 자동 새로고침

[theme]
backgroundColor = "#f2e2feed"
primaryColor = "#f80677ee"
secondaryBackgroundColor="#f8facaff"
textColor = "#0c020ff1"
